# Settings
@hostname = localhost
@port = 4000
@host = {{hostname}}:{{port}}/api/v1
@contentType = application/json
@token = ""

###
# Retrieve hello world!
GET http://{{host}}/hello HTTP/1.1
Content-Type: {{contentType}}

###
# Retrieve hello joe!
GET http://{{host}}/hello/joe HTTP/1.1
Content-Type: {{contentType}}

###
# Register user
# @name createuser
POST http://{{host}}/users HTTP/1.1
Content-Type: {{contentType}}

{
    "firstName": "joe",
    "lastName": "doe",
    "email": "joedoe@gmail.com",
    "password": "joedoe123"
}

###
# Login user
# @name login
@token={{login.response.body.token}}
POST http://{{host}}/auth/login HTTP/1.1
Content-Type: {{contentType}}

{
    "email": "joe.doe@gmail.com",
    "password": "joedoe123"
}

###
# Retrieve all users
GET http://{{host}}/users HTTP/1.1
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

###
# Retrieve a user
@userId = {{createuser.response.body.id}}
GET http://{{host}}/users/{{userId}} HTTP/1.1
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

###
# Update a user profile
@userId = {{createuser.response.body.id}}
PUT http://{{host}}/users/{{userId}} HTTP/1.1
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
    "firstName": "Joe",
    "lastName": "Doe",
    "email": "joe.doe@gmail.com"
}


###
# Delete a user profile
@userId = {{createuser.response.body.id}}
DELETE http://{{host}}/users/{{userId}} HTTP/1.1
Content-Type: {{contentType}}
Authorization: Bearer {{token}}


### Swagger Documentation
GET http://{{host}}/documentation
